### ISSUE TITLE
Unable to build on ubuntu 24.0.4

### ISSUE THREAD

**Issue by csod-bganatra** [y-a-v-a/node-gd#104]
Hello @y-a-v-a 

I have been trying to build this code on ubuntu 24.0.4 docker image and getting this error 

```
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build', '--jobs', 5 ]
make: Entering directory '/root/node-gd/build'
  CC(target) Release/obj.target/nothing/node_modules/node-addon-api/nothing.o
rm -f Release/obj.target/node_modules/node-addon-api/nothing.a Release/obj.target/node_modules/node-addon-api/nothing.a.ar-file-list; mkdir -p `dirname Release/obj.target/node_modules/node-addon-api/nothing.a`
ar crs Release/obj.target/node_modules/node-addon-api/nothing.a @Release/obj.target/node_modules/node-addon-api/nothing.a.ar-file-list
  COPY Release/nothing.a
  CXX(target) Release/obj.target/node_gd/src/addon.o
In file included from ../src/addon.cc:20:
../src/node_gd.cc: In member function 'Napi::Value Gd::Image::Heif(const Napi::CallbackInfo&)':
../src/node_gd.cc:650:10: error: 'SaveHeifWorker' has not been declared
  650 |   return SaveHeifWorker::DoWork(info, this->_image);
      |          ^~~~~~~~~~~~~~
make: *** [node_gd.target.mk:139: Release/obj.target/node_gd/src/addon.o] Error 1
make: Leaving directory '/root/node-gd/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack at ChildProcess.<anonymous> (/usr/lib/node_modules/node-gyp/lib/build.js:216:23)
gyp ERR! System Linux 6.12.5-linuxkit
gyp ERR! command "/usr/bin/node" "/usr/bin/node-gyp" "rebuild" "-j" "max"
gyp ERR! cwd /root/node-gd
gyp ERR! node -v v22.14.0
gyp ERR! node-gyp -v v11.1.0
gyp ERR! not ok 
```

I am doing `npm install` and it is running `node-gyp rebuild -j max` as far as I can understand and it is failing, 

I have install libdh-dev package as well.
